-- =============================================================
-- TENANT FK ENFORCEMENT RULE
-- =============================================================
-- All future app tables MUST include:
--   tenant_id uuid REFERENCES app.tenants(id) NOT NULL
--
-- This enforces tenant isolation at the data model layer.
-- Combined with RLS policies, ensures no cross-tenant data leakage.
--
-- Example:
--   CREATE TABLE IF NOT EXISTS app.orders (
--       id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--       tenant_id   uuid NOT NULL REFERENCES app.tenants(id),
--       created_at  timestamptz DEFAULT now()
--   );
--   ALTER TABLE app.orders ENABLE ROW LEVEL SECURITY;
--
-- This file is a documentation-only migration.
-- It contains no executable SQL statements.
-- =============================================================
